/* =============================================
 Author:		Rafael Turra Silva
 Create date:	2017-02-23
 Description:	Query para itens do romaneio.
				- Verifica a marca;
				- Local;
				- Descrição;
				- Complemento;
				- Referência do fornecedor;
				- Unidade;
				- Quantidade;
 ============================================= */
SELECT	ITE.CODPROD,
		RTRIM(PRO.DESCRPROD) AS DESCRPROD,
		RTRIM(PRO.COMPLDESC) AS COMPLDESC,
		SUM(ITE.QTDNEG) AS QTDNEG,
		ITE.CODVOL,
		ICP.CODMATPRIMA,
		ICP.CODVOL ICPCODVOL,
		ICP.QTDMISTURA as QTDMISTURA,
		ICP.AD_OBSERVACAO,
		RTRIM(COM.DESCRPROD) COMDESCRPROD,
		RTRIM(COM.COMPLDESC) COMCOMPLDESC,
		CASE WHEN ITE.CODVOL = 'KT' THEN '' ELSE (CASE WHEN PRO.CODPROD IS NOT NULL THEN ISNULL(RTRIM(LOCKT.DESCRLOCAL), ISNULL(RTRIM(LSECD.DESCRLOCAL),''))
													   ELSE ISNULL(RTRIM(LOCR.DESCRLOCAL), '')
												  END)
		END AS LOCAL_PRODUTO,
		CASE WHEN COM.CODPROD IS NULL THEN '' ELSE ISNULL(RTRIM(LOCR.DESCRLOCAL),ISNULL(LSECR.DESCRLOCAL,'')) END AS LOCAL_COMPONENTE,
		ISNULL(RTRIM(PRO.REFFORN),'') AS REFFORNPRO,
		ISNULL(RTRIM(COM.REFFORN),'') AS REFFORNCOM,
		CASE WHEN PRO.CODVOL = 'KT' THEN '' ELSE (CASE WHEN PRO.DESCRPROD = PRO.MARCA THEN '' ELSE (CASE WHEN PRO.DESCRPROD IS NULL THEN '' ELSE ISNULL(RTRIM(PRO.MARCA),'') END) END) END AS MARCAPRO,
		CASE WHEN COM.DESCRPROD IS NULL THEN '' ELSE ISNULL(RTRIM(COM.MARCA),'') END AS MARCACOM
FROM	sankhya.TGFITE ITE
		INNER JOIN sankhya.TGFPRO PRO ON(ITE.CODPROD = PRO.CODPROD)
		LEFT JOIN sankhya.TGFICP ICP ON(ITE.CODPROD = ICP.CODPROD)
		LEFT JOIN sankhya.TGFPRO COM ON(ICP.CODMATPRIMA = COM.CODPROD)
		LEFT JOIN sankhya.TGFLOC LOCR WITH(NOLOCK) ON COM.CODLOCALPADRAO = LOCR.CODLOCAL
		LEFT JOIN sankhya.TGFLOC LOCD WITH(NOLOCK) ON PRO.CODLOCALPADRAO = LOCD.CODLOCAL
		LEFT JOIN sankhya.TGFLOC LOCKT WITH(NOLOCK) ON PRO.CODLOCALPADRAO = LOCKT.CODLOCAL
		LEFT JOIN (select CODPROD, MIN(CODLOC) AS CODLOC from sankhya.AD_LOCSEC WITH(NOLOCK) GROUP BY CODPROD) LOCSECR ON LOCSECR.CODPROD = COM.CODPROD
		LEFT JOIN (select CODPROD, MIN(CODLOC) AS CODLOC from sankhya.AD_LOCSEC WITH(NOLOCK) GROUP BY CODPROD) LOCSECD ON LOCSECD.CODPROD = PRO.CODPROD
		LEFT JOIN sankhya.TGFLOC LSECR WITH(NOLOCK) ON LSECR.CODLOCAL = LOCSECR.CODLOC
		LEFT JOIN sankhya.TGFLOC LSECD WITH(NOLOCK) ON LSECD.CODLOCAL = LOCSECD.CODLOC
WHERE	ITE.USOPROD = 'R' and
		ITE.NUNOTA = $P{NUNOTA}
GROUP BY
		ITE.CODPROD,
		RTRIM(PRO.DESCRPROD),
		RTRIM(PRO.COMPLDESC),
		ITE.CODVOL,
		ICP.CODMATPRIMA,
		ICP.CODVOL,
		ICP.AD_OBSERVACAO,
		RTRIM(COM.DESCRPROD),
		RTRIM(COM.COMPLDESC),
		ICP.QTDMISTURA,
		ISNULL(RTRIM(PRO.REFFORN),''),
		ISNULL(RTRIM(COM.REFFORN), ''),
		CASE WHEN ITE.CODVOL = 'KT' THEN '' ELSE (CASE WHEN PRO.CODPROD IS NOT NULL THEN ISNULL(RTRIM(LOCKT.DESCRLOCAL), ISNULL(RTRIM(LSECD.DESCRLOCAL),''))
													   ELSE ISNULL(RTRIM(LOCR.DESCRLOCAL), '')
												  END)
		END,
		CASE WHEN COM.CODPROD IS NULL THEN '' ELSE ISNULL(RTRIM(LOCR.DESCRLOCAL),ISNULL(LSECR.DESCRLOCAL,'')) END,
		CASE WHEN PRO.CODVOL = 'KT' THEN '' ELSE (CASE WHEN PRO.DESCRPROD = PRO.MARCA THEN '' ELSE (CASE WHEN PRO.DESCRPROD IS NULL THEN '' ELSE ISNULL(RTRIM(PRO.MARCA),'') END) END) END ,
		CASE WHEN COM.DESCRPROD IS NULL THEN '' ELSE ISNULL(RTRIM(COM.MARCA),'') END