USE SANKHYA_PRODUCAO
GO
ALTER DATABASE SANKHYA_PRODUCAO SET RECOVERY SIMPLE WITH NO_WAIT
DBCC SHRINKFILE(2, TRUNCATEONLY)
ALTER DATABASE SANKHYA_PRODUCAO SET RECOVERY FULL WITH NO_WAIT
GO

-- SANKHYA_HOMOLOGACAO
-- SANKHYA_PRODUCAO