USE SANKHYA_PRODUCAO;

SELECT * FROM sankhya.AD_CPENVIOS AS C WITH (NOLOCK)
WHERE VLRFRETE IS NULL 
AND DTENVIO < CONVERT(VARCHAR, DATEADD(DAY, -1, GETDATE()), 23)
AND STATUS IN ('N','T','E')
AND TRACKER = 'M'
ORDER BY DTENVIO


