DECLARE 
@CODPARCWRONG	INT,
@CODPARCCORRECT	INT;


SET @CODPARCWRONG = ;
SET @CODPARCCORRECT = ;

UPDATE sankhya.TGFFIN SET CODPARC = @CODPARCCORRECT WHERE CODPARC = @CODPARCWRONG;
UPDATE sankhya.TGFCAB SET CODPARC = @CODPARCCORRECT WHERE CODPARC = @CODPARCWRONG;
UPDATE sankhya.TGFCPL SET CODPARC = @CODPARCCORRECT WHERE CODPARC = @CODPARCWRONG;
DELETE FROM sankhya.TGFPAR WHERE CODPARC = @CODPARCWRONG;