SELECT PAR.NOMEPARC, FIN.NOSSONUM, FIN.DTVENC, 25 AS 'CARTEIRA', FIN.DTNEG, FIN.VLRDESDOB, PAR.CGC_CPF, PAR.CEP, BAI.NOMEBAI, CID.NOMECID, CID.UF, EST.UF
FROM sankhya.TGFCAB AS CAB WITH(NOLOCK)
INNER JOIN sankhya.TGFFIN AS FIN WITH(NOLOCK) ON CAB.NUNOTA = FIN.NUNOTA
INNER JOIN sankhya.TGFPAR AS PAR WITH(NOLOCK) ON PAR.CODPARC = CAB.CODPARC 
LEFT JOIN sankhya.TSICID AS CID WITH(NOLOCK) ON CID.CODCID = PAR.CODCID 
LEFT JOIN sankhya.TSIUFS AS EST WITH(NOLOCK) ON CID.UF = EST.CODUF
LEFT JOIN sankhya.TSIBAI AS BAI WITH(NOLOCK) ON PAR.CODBAI = BAR.CODBAI
LEFT JOIN sankhya.TSIEND AS ENDE WITH(NOLOCK) ON ENDE.CODEND = PAR.CODEND
WHERE
-- FILTRAR NOSSO NUMERO MAIOR QUE 8 CARACTERES
LEN(FIN.NOSSONUM) = 12 
-- FILTRAR SOMENTE CONTA BANCÁRIA BRADESCO (4)
AND FIN.CODCTABCOINT = 4
-- FILTRAR TIPO DE TÍTULO BOLETO BRADESCO
AND FIN.CODTIPTIT = 14
-- FILTRAR PEDIDOS QUE AINDA NÃO FORAM PAGOS
AND FIN.VLRBAIXA = 0
-- FILTRAR PELA TOP DE VENDAS
AND CAB.CODTIPOPER IN (500,501,503,515)
-- FILTRAR PEDIDOS DOS ÚLTIMOS 30 DIAS
AND CAB.DTNEG >= DATEADD(DAY,-31,GETDATE())
--GROUP BY FIN.NOSSONUM
--ORDER BY CAB.DTNEG DESC;
-- CAB.NUNOTA (NUMERO UNICO)
-- CAB.NUMNOTA (NUMERO DA TOP)
-- CAB.AD_PEDORIGINAL
-- CAB.AD_PEDIDOWMW
--
--
-- 502 - ECOMMERCE - PEDIDO VTEX
-- NUMNOTA: 5326123
--
-- 501 - CALL CENTER RECEPTIVO
-- 1, 2, 3, 4 ...
--
--
--
--SELECT * FROM SANKHYA_PRODUCAO.sankhya.TSIUFS