DECLARE 
@PEDORIGINAL INT,
@NUNOTA INT;

SET @PEDORIGINAL = 490035;

ALTER TABLE sankhya.TGFCAB DISABLE TRIGGER ALL;
ALTER TABLE sankhya.TGFITE DISABLE TRIGGER ALL;

DECLARE notas CURSOR FAST_FORWARD FOR
SELECT NUNOTA
FROM sankhya.TGFCAB WITH (NOLOCK)
WHERE AD_PEDORIGINAL = @PEDORIGINAL;

OPEN notas;

FETCH NEXT FROM notas INTO @NUNOTA;

WHILE @@FETCH_STATUS = 0
BEGIN	
	UPDATE sankhya.TGFITE SET PENDENTE = 'N', QTDENTREGUE = QTDNEG WHERE NUNOTA = @NUNOTA;
	UPDATE sankhya.TGFCAB SET PENDENTE = 'N', AD_STATUSPGTO = 'E' WHERE NUNOTA = @NUNOTA;
	FETCH NEXT FROM notas INTO @NUNOTA;
END

CLOSE notas;
DEALLOCATE notas;

ALTER TABLE sankhya.TGFITE ENABLE TRIGGER ALL;
ALTER TABLE sankhya.TGFCAB ENABLE TRIGGER ALL;