DECLARE 
@NUNOTA INT,
@CODPROD INT,
@QTDNEG FLOAT;

SET @NUNOTA = 904239;

UPDATE sankhya.TGFITE SET PENDENTE = 'S', QTDENTREGUE = 0 WHERE NUNOTA = @NUNOTA;
UPDATE sankhya.TGFCAB SET PENDENTE = 'S', AD_STATUSPGTO = 'P' WHERE NUNOTA = @NUNOTA;

ALTER TABLE sankhya.TGFVAR DISABLE TRIGGER ALL;
DELETE FROM sankhya.TGFVAR WHERE NUNOTA != @NUNOTA AND NUNOTAORIG = @NUNOTA;
ALTER TABLE sankhya.TGFVAR ENABLE TRIGGER ALL;

DECLARE cursorItens CURSOR FAST_FORWARD FOR
SELECT I.CODPROD, I.QTDNEG
FROM sankhya.TGFITE AS I WITH (NOLOCK)
WHERE I.NUNOTA = @NUNOTA;

OPEN cursorItens;

FETCH NEXT FROM cursorItens
INTO @CODPROD, @QTDNEG;
	
WHILE @@FETCH_STATUS = 0
BEGIN
	IF EXISTS (
		SELECT 1
		FROM sankhya.TGFEST WITH (NOLOCK)
		WHERE CODPROD = @CODPROD
	)
		UPDATE sankhya.TGFEST
		SET ESTOQUE = ESTOQUE + @QTDNEG,
			RESERVADO = RESERVADO + @QTDNEG
		WHERE CODPROD = @CODPROD;
	ELSE
		INSERT INTO sankhya.TGFEST (CODEMP, CODLOCAL, ESTOQUE, CODPROD, RESERVADO)
		VALUES (1, 0, @QTDNEG, @CODPROD, @QTDNEG);

	IF EXISTS (
		SELECT 1
		FROM sankhya.TGFPRO WITH (NOLOCK)
		WHERE CODPROD = @CODPROD 
		AND ATIVO != 'S'
	)
	BEGIN
		ALTER TABLE sankhya.TGFPRO
		DISABLE TRIGGER ALL;

		UPDATE sankhya.TGFPRO
		SET ATIVO = 'S'
		WHERE CODPROD = @CODPROD;

		ALTER TABLE sankhya.TGFPRO
		ENABLE TRIGGER ALL;
	END

	FETCH NEXT FROM cursorItens
	INTO @CODPROD, @QTDNEG;
END
CLOSE cursorItens;
DEALLOCATE cursorItens;