USE SANKHYA_PRODUCAO;

SELECT F.NUNOTA, F.PEDORIGINAL, E.CODPARC, E.DHEXCLUSAO
FROM sankhya.AD_PEDIDOVTEXSCFLUXO AS F WITH (NOLOCK)
INNER JOIN sankhya.TGFCAB_EXC AS E WITH (NOLOCK)
ON E.NUNOTA = F.NUNOTA
WHERE F.PEDORIGINAL IN (
	SELECT P.PEDORIGINAL
	FROM sankhya.AD_PEDIDOVTEXSC AS P WITH (NOLOCK)
	WHERE CODPARC IS NULL
) AND F.OCORRENCIA = 'P'
AND EXISTS(SELECT 1 FROM sankhya.TGFPAR WHERE CODPARC = E.CODPARC)
ORDER BY E.DHEXCLUSAO DESC

SELECT F.NUNOTA, F.PEDORIGINAL, R.CODPARC
FROM sankhya.AD_PEDIDOVTEXSCFLUXO AS F WITH (NOLOCK)
INNER JOIN sankhya.TGFCAN AS R WITH (NOLOCK)
ON R.NUNOTA = F.NUNOTA
WHERE F.PEDORIGINAL IN (
	SELECT P.PEDORIGINAL
	FROM sankhya.AD_PEDIDOVTEXSC AS P WITH (NOLOCK)
	WHERE CODPARC IS NULL
) AND F.OCORRENCIA = 'P'
AND EXISTS(SELECT 1 FROM sankhya.TGFPAR WHERE CODPARC = R.CODPARC)
ORDER BY R.DTCANC DESC


SELECT P.PEDORIGINAL, C.CODPARC
FROM sankhya.AD_PEDIDOVTEXSC AS P WITH (NOLOCK)
INNER JOIN sankhya.TGFCAB AS C WITH (NOLOCK)
ON C.AD_PEDORIGINAL = P.PEDORIGINAL
WHERE P.CODPARC IS NULL
AND EXISTS (SELECT 1 FROM sankhya.TGFPAR WHERE CODPARC = C.CODPARC)
