SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Rafael Turra
-- Create date: 2017-02-03
-- Description:	ATUALIZA O CÓDIGO LOCAL E (ESTOQUE E RESERVADO) DO LOCAL VIRTUAL 990000000
-- =============================================
ALTER TRIGGER [sankhya].[TRG_INC_UPD_TGFEST_TGFITE] 
   ON  [sankhya].TGFITE 
   AFTER INSERT
AS 

DECLARE
	@CODPROD	INT,
	@CODLOCAL	INT,
	@QTDNEG		DECIMAL(10,2),
	@DISPONIVEL DECIMAL(10,2),
	@SEQUENCIA	INT,
	@NUNOTA		INT
	
BEGIN
	SET NOCOUNT ON;
	-- VERIFICANDO SE É CODTIPOPER = 505 AND COLOCAL = 0 
	IF NOT EXISTS (SELECT 1
					FROM	SANKHYA.TGFCAB CAB WITH (NOLOCK)
							INNER JOIN INSERTED I ON I.NUNOTA = CAB.NUNOTA
					WHERE	CAB.CODTIPOPER = 505 AND I.CODLOCALORIG = 990000000)					
		RETURN;

	-- BUSCANDO O PRODUTO DA NOTA
	SELECT	@CODPROD = I.CODPROD,
			@QTDNEG = I.QTDNEG,
			@NUNOTA = I.NUNOTA,
			@SEQUENCIA = I.SEQUENCIA
	FROM	INSERTED I

	-- SELECIONAR O LOCAL NOVO
	SELECT	@CODLOCAL = CODLOCAL,
			@DISPONIVEL = ESTOQUE - RESERVADO
	FROM	SANKHYA.TGFEST
	WHERE	CODLOCAL BETWEEN 10000000 AND 19999999
			AND CODPROD = @CODPROD
	
	-- SE NÃO TIVER ESTOQUE NO LOCAL REALIZAR TRANSFERÊNCIA
	IF (@CODLOCAL IS NULL OR @DISPONIVEL < @QTDNEG)
		RAISERROR ('NÃO EXISTE ESTOQUE SUFICIENTE NO ESTOQUE 1 PARA O PRODUTO %i', 16, 1, @CODPROD)
	UPDATE SANKHYA.TGFITE SET CODLOCALORIG = @CODLOCAL WHERE CODPROD = @CODPROD AND NUNOTA = @NUNOTA;
	UPDATE SANKHYA.TGFEST SET RESERVADO = RESERVADO + @QTDNEG WHERE CODPROD = @CODPROD AND CODLOCAL = @CODLOCAL;
	UPDATE SANKHYA.TGFEST SET RESERVADO = RESERVADO - @QTDNEG WHERE CODPROD = @CODPROD AND CODLOCAL = 990000000;
END
GO